### ISSUE TITLE
Display Warnings on load of plugins?

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#178]
Especially plugin holidays-calculator searches for a file containing the holiday definitions during start-up.
If there is no such file, plugin could still be running, falling back on an empty list of holidays. 
On the other hand the plugin maybe still wants to inform the user that she might want to provide such a file in order to make full use of the plugin.

In such case the plugin could display a friendly warning to the user but does not need to stop start-up of WhiteRabbit. 

The current ticket therefore proposes to enhance WhiteRabbit jfxui to enable the display of warnings during start-up without aborting start-up process.

**Comment by ckunki** [comment]
Hi @kaklakariada what do you think about this proposal?

**Comment by ckunki** [comment]
Proposed location: `jfxui/.../SplashScreenLoader.:createAlert()`

**Comment by ckunki** [comment]
Does not look that easy.

Probably a general notification mechanism is required. SplashScreenLoader already extends Preloader and hence could offer such a mechanism as Preloader is documented to get notification of progress and the like.

But WR needs to pass a notification callback to each plugin. and in case a plugin discovers problems the plugin then can call the callback but control remains in the plugin to continue start-up.

**Comment by kaklakariada** [comment]
I see three options:

1. Your proposal with a callback.
2. The plugin itself opens a JFX dialog with a warning method.
3. The plugin just throws an exception. WR will show an error dialog and stop startup.

I prefer option 3 because
* It's less invasive, less effort, does not change the API
* As a user I have two options:
  * Either I click away the warning at every start and start getting annoyed
  * Or I fix the configuration issue
* I would prefer if the user fixes the configuration problem. And a failing startup is the best way to force them to fix the problem.

**Comment by ckunki** [comment]
I agree.
While playing a little bit around I also found that option 3 is least effort, minimum invasive and also establishes a clear policy ind the sense of your comment.

I propose to close the ticket.
